routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::redirect('/',  url('/home'));

Route::group(['middleware' => ['auth']], function () {
    // HOME ROUTE
    Route::get('/home', 'HomeController@index')->name('home');

    // AUXILIAR ROUTES
    Route::get('/contacts/types', 'ContactController@types')->name('contacts.types');
    Route::get('/breakdowns/types', 'BreakdownController@types')->name('breakdowns.types');
    Route::get('/breakdowns/items/types', 'BreakdownController@itemsTypes')->name('breakdowns.items.types');
    Route::get('/breakdowns/status', 'BreakdownController@status')->name('breakdowns.status');
    Route::get('/breakdowns/{id}/items/', 'BreakdownController@items')->name('breakdowns.items');
    Route::get('/price-differences/{id}/items/', 'PriceDifferenceController@items')->name('price-differences.items');
    Route::get('/price-differences/status', 'PriceDifferenceController@status')->name('price-differences.status');
    Route::get('/protocols/status', 'ProtocolController@status')->name('protocols.status');
    Route::get('/protocols/{id}/items/', 'ProtocolController@items')->name('protocols.items');
    Route::get('/equipments/list/', 'EquipmentController@list')->name('equipments.list');
    Route::get('/validities/status', 'ValidityController@status')->name('validities.status');

	//PROFILE ROUTES
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
    Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
    Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

    // REPORTS ROUTES
    Route::get('/reports/credit-analysis', 'ReportsController@creditAnalysisIndex')->name('credit-analysis.index');
    Route::post('/reports/credit-analysis', 'ReportsController@creditAnalysisPost')->name('credit-analysis.post');
    Route::get('/reports/validities', 'ReportsController@validitiesIndex')->name('validities-report.index');
    Route::post('/reports/validities', 'ReportsController@validitiesPost')->name('validities-report.post');

    //ADMINISTRATIVE ROUTES
    Route::get('/admin/sped/', 'AdministrativeController@sped')->name('admin.sped');
    Route::post('/admin/sped/', 'AdministrativeController@spedPost')->name('admin.spedPost');
    Route::get('/admin/xml/', 'AdministrativeController@xml')->name('admin.xml');
    Route::post('/admin/xml/', 'AdministrativeController@xmlPost')->name('admin.xmlPost');
    Route::post('/admin/xml-database/{id}', 'AdministrativeController@xmlDatabase')->name('admin.xmlDb');
    Route::get('/admin/csv/export', 'AdministrativeController@csvExport')->name('admin.csv_export');
    Route::post('/admin/csv/export', 'AdministrativeController@csvPostExport')->name('admin.csvPost_export');
    Route::get('/admin/csv/import', 'AdministrativeController@csvImport')->name('admin.csv_import');
    Route::post('/admin/csv/import', 'AdministrativeController@csvPostImport')->name('admin.csvPost_import');

    // PDF ROUTES
    Route::post('/pdf/{view}/', 'PDFController@generate')->name('pdf.generate');

    // PRODUCT ROUTES
    Route::get('/products/{cod_aux}', 'ProductController@getProduct')->name('product.get');

    // CRUD ROUTES
    Route::resources([
        'contacts'              => 'ContactController',
        'breakdowns'            => 'BreakdownController',
        'recounts'              => 'RecountController',
        'price-differences'     => 'PriceDifferenceController',
        'protocols'             => 'ProtocolController',
        'equipments'            => 'EquipmentController',
        'factors'               => 'FactorController',
        'validities'            => 'ValidityController',
		'users'      			=> 'UserController',
    ]);
});

resources/views/layouts/navbars/navs/auth.blade.php
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent  bg-primary  navbar-absolute">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-bar navbar-kebab"></span>
      <span class="navbar-toggler-bar navbar-kebab"></span>
      <span class="navbar-toggler-bar navbar-kebab"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navigation">
      <form action="{{ $searchRoute ?? route('home') }}">
          @csrf
        <div class="input-group no-border">
          <input type="text" name="q" class="form-control" placeholder="{{ 'Buscar...' }}">
          <div class="input-group-append">
            <div class="input-group-text">
              <i class="now-ui-icons ui-1_zoom-bold"></i>
            </div>
          </div>
        </div>
      </form>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
            @if($agent->isMobile())
                @include('layouts.navbars.navs.sidebar-mobile')

            @else
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="now-ui-icons users_single-02"></i>
                    <p>
                        <span class="d-lg-none d-md-block">{{ __("Account") }}</span>
                    </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{{ route('profile.edit') }}">
                        {{ __("Meu perfil") }}
                    </a>
                    <a class="logout dropdown-item" href="#">
                        {{ __('Logout') }}
                    </a>
                </div>
            @endif
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- End Navbar -->

resources/views/layouts/navbars/navs/guest.blade.php
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-transparent  bg-primary  navbar-absolute">
  <div class="container-fluid">
    <div class="navbar-wrapper">
    <a class="navbar-brand" href="#">{{ $namePage }}</a>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-bar navbar-kebab"></span>
      <span class="navbar-toggler-bar navbar-kebab"></span>
      <span class="navbar-toggler-bar navbar-kebab"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navigation">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{{ route('login') }}" class="nav-link">
            <i class="now-ui-icons design_app"></i> {{ __("Dashboard") }}
          </a>
        </li>
        <li class="nav-item @if ($activePage == 'register') active @endif">
          <a href="{{ route('register') }}" class="nav-link">
            <i class="now-ui-icons tech_mobile"></i> {{ __("Registro") }}
          </a>
        </li>
        <li class="nav-item @if ($activePage == 'login') active @endif ">
          <a href="{{ route('login') }}" class="nav-link">
            <i class="now-ui-icons users_circle-08"></i> {{ __("Login") }}
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- End Navbar -->

resources/views/layouts/navbars/navs/sidebar-mobile.blade.php
    <li class="nav-item dropdown @if ($activePage == 'home') active @endif">
        <a class="nav-link" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="now-ui-icons design_app"></i>
            <p>{{ __('Dashboard') }}</p>
        </a>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{{ route('home') }}">Página Inicial</a>
        </div>
    </li>
    <li class = "nav-item dropdown @if ($activePage == 'contacts') active @endif">
        <a class="nav-link" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="now-ui-icons education_agenda-bookmark"></i>
            <p>{{ __('Contatos') }}</p>
        </a>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{{ route('contacts.index') }}"><strong>Todos</strong></a>
            <a class="dropdown-item" href="{{ route('contacts.index', ['t' => \App\Entities\Contact::COLABORADOR]) }}">Colaboradores</a>
            <a class="dropdown-item" href="{{ route('contacts.index', ['t' => \App\Entities\Contact::FORNECEDOR]) }}">Fornecedores</a>
            <a class="dropdown-item" href="{{ route('contacts.index', ['t' => \App\Entities\Contact::REPRESENTANTE]) }}">Representantes</a>
            <a class="dropdown-item" href="{{ route('contacts.index', ['t' => \App\Entities\Contact::PROVEDOR_DE_SERVICO]) }}">Provedores de Serviços</a>
            <a class="dropdown-item" href="{{ route('contacts.index', ['t' => \App\Entities\Contact::EMPRESA_GRUPO]) }}">Empresas do grupo</a>
            <a class="dropdown-item" href="{{ route('contacts.index', ['t' => \App\Entities\Contact::SUPORTE]) }}">Suporte</a>
        </div>
    </li>
    <li class = "nav-item dropdown @if ($activePage == 'cpd') active @endif">
        <a class="nav-link" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="now-ui-icons business_briefcase-24"></i>
            <p>{{ __('CPD') }}</p>
        </a>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{{ route('breakdowns.index') }}">Avaria e falta</a>
            <a class="dropdown-item" href="{{ route('recounts.index') }}">Conferência manual</a>
            <a class="dropdown-item" href="{{ route('validities.index') }}">Controle de vencimentos</a>
            <a class="dropdown-item" href="{{ route('price-differences.index') }}">Diferênça de preços</a>
            <a class="dropdown-item" href="{{ route('factors.index') }}">Fatores</a>
        </div>
    </li>
    <li class = "nav-item dropdown @if ($activePage == 'equipments') active @endif">
        <a class="nav-link" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="now-ui-icons tech_laptop"></i>
            <p>{{ __('Equipamentos') }}</p>
        </a>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{{ route('equipments.index') }}"><strong>Todos</strong></a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_MONITORS]) }}">Monitores</a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_PCS]) }}">Computadores</a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_KEYBOARDS]) }}">Teclados</a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_MOUSES]) }}">Mouses</a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_CODEBAR_READERS]) }}">Leitores</a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_PRINTERS]) }}">Impressoras</a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_TONERS]) }}">Toners</a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_FONTS]) }}">Fontes</a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_NOBREAKS]) }}">Nobreaks</a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_BATTERYS]) }}">Baterias</a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_DATA_COLECTORS]) }}">Coletores</a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_TABLETS]) }}">Tablets</a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_CAMERAS_DVR_NVR]) }}">Cameras</a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_HDS]) }}">HDs</a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_PROCESSORS]) }}">Processadores</a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_RAM]) }}">Memória</a>
            <a class="dropdown-item" href="{{ route('equipments.index', ['t' => \App\Entities\Equipment::TYPE_OTHERS]) }}">Outros</a>
        </div>
    </li>
    <li class = "nav-item dropdown @if ($activePage == 'protocols') active @endif">
        <a class="nav-link" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="now-ui-icons files_single-copy-04"></i>
            <p>{{ __('Protocolos') }}</p>
        </a>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{{ route('protocols.index', ['t' => \App\Entities\Protocol::TYPE_EQUIPMENT]) }}">Protocolo de Equipamentos</a>
            <a class="dropdown-item" href="{{ route('protocols.index', ['t' => \App\Entities\Protocol::TYPE_PRODUCT]) }}">Protocolo de Entrada de Mercadoria</a>
        </div>
    </li>

    <li class = "nav-item dropdown @if ($activePage == 'reports') active @endif">
        <a class="nav-link" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="now-ui-icons files_box"></i>
            <p>{{ __('Relatórios') }}</p>
        </a>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{{ route('credit-analysis.index') }}">Análise de Crédito</a>
            <a class="dropdown-item" href="{{ route('validities-report.index') }}">Controle de Validades</a>
        </div>
    </li>

    <li class="nav-item dropdown @if ($activePage == 'csv') active @endif">
        <a class="nav-link" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="now-ui-icons design_app"></i>
            <p>{{ __('Ferramenta para E-commerce') }}</p>
        </a>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{{ route('admin.csv') }}">Exportação de Catálogo</a>
        </div>
    </li>

    @if(auth()->user()->is_admin)
    <li class="nav-item dropdown @if ($activePage == 'users') active @endif">
        <a class="nav-link" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="now-ui-icons design_app"></i>
            <p>{{ __('Controle de Usuários') }}</p>
        </a>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{{ route('users.index') }}">Listar usuários</a>
        </div>
    </li>
    @endif
    <li class="nav-item dropdown @if ($activePage == 'users') active @endif">
        <a class="nav-link" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="now-ui-icons users_single-02"></i>
            <p>
                <span class="d-lg-none d-md-block">{{ __("Conta") }}</span>
            </p>
        </a>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{{ route('profile.edit') }}">
                {{ __("Meu perfil") }}
            </a>
            <a class="logout dropdown-item" href="#">
                {{ __('Logout') }}
            </a>
        </div>
    </li>